// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lapis.proto

#ifndef PROTOBUF_lapis_2eproto__INCLUDED
#define PROTOBUF_lapis_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace lapis {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_lapis_2eproto();
void protobuf_AssignDesc_lapis_2eproto();
void protobuf_ShutdownFile_lapis_2eproto();

class SystemConfProto;

// ===================================================================

class SystemConfProto : public ::google::protobuf::Message {
 public:
  SystemConfProto();
  virtual ~SystemConfProto();

  SystemConfProto(const SystemConfProto& from);

  inline SystemConfProto& operator=(const SystemConfProto& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SystemConfProto& default_instance();

  void Swap(SystemConfProto* other);

  // implements Message ----------------------------------------------

  SystemConfProto* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SystemConfProto& from);
  void MergeFrom(const SystemConfProto& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 coordinator = 1;
  inline bool has_coordinator() const;
  inline void clear_coordinator();
  static const int kCoordinatorFieldNumber = 1;
  inline ::google::protobuf::int32 coordinator() const;
  inline void set_coordinator(::google::protobuf::int32 value);

  // required int32 worker_start = 2;
  inline bool has_worker_start() const;
  inline void clear_worker_start();
  static const int kWorkerStartFieldNumber = 2;
  inline ::google::protobuf::int32 worker_start() const;
  inline void set_worker_start(::google::protobuf::int32 value);

  // required int32 worker_end = 3;
  inline bool has_worker_end() const;
  inline void clear_worker_end();
  static const int kWorkerEndFieldNumber = 3;
  inline ::google::protobuf::int32 worker_end() const;
  inline void set_worker_end(::google::protobuf::int32 value);

  // optional int32 memory_start = 4;
  inline bool has_memory_start() const;
  inline void clear_memory_start();
  static const int kMemoryStartFieldNumber = 4;
  inline ::google::protobuf::int32 memory_start() const;
  inline void set_memory_start(::google::protobuf::int32 value);

  // optional int32 memory_end = 5;
  inline bool has_memory_end() const;
  inline void clear_memory_end();
  static const int kMemoryEndFieldNumber = 5;
  inline ::google::protobuf::int32 memory_end() const;
  inline void set_memory_end(::google::protobuf::int32 value);

  // optional int32 disk_start = 6;
  inline bool has_disk_start() const;
  inline void clear_disk_start();
  static const int kDiskStartFieldNumber = 6;
  inline ::google::protobuf::int32 disk_start() const;
  inline void set_disk_start(::google::protobuf::int32 value);

  // optional int32 disk_end = 7;
  inline bool has_disk_end() const;
  inline void clear_disk_end();
  static const int kDiskEndFieldNumber = 7;
  inline ::google::protobuf::int32 disk_end() const;
  inline void set_disk_end(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:lapis.SystemConfProto)
 private:
  inline void set_has_coordinator();
  inline void clear_has_coordinator();
  inline void set_has_worker_start();
  inline void clear_has_worker_start();
  inline void set_has_worker_end();
  inline void clear_has_worker_end();
  inline void set_has_memory_start();
  inline void clear_has_memory_start();
  inline void set_has_memory_end();
  inline void clear_has_memory_end();
  inline void set_has_disk_start();
  inline void clear_has_disk_start();
  inline void set_has_disk_end();
  inline void clear_has_disk_end();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 coordinator_;
  ::google::protobuf::int32 worker_start_;
  ::google::protobuf::int32 worker_end_;
  ::google::protobuf::int32 memory_start_;
  ::google::protobuf::int32 memory_end_;
  ::google::protobuf::int32 disk_start_;
  ::google::protobuf::int32 disk_end_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(7 + 31) / 32];

  friend void  protobuf_AddDesc_lapis_2eproto();
  friend void protobuf_AssignDesc_lapis_2eproto();
  friend void protobuf_ShutdownFile_lapis_2eproto();

  void InitAsDefaultInstance();
  static SystemConfProto* default_instance_;
};
// ===================================================================


// ===================================================================

// SystemConfProto

// required int32 coordinator = 1;
inline bool SystemConfProto::has_coordinator() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SystemConfProto::set_has_coordinator() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SystemConfProto::clear_has_coordinator() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SystemConfProto::clear_coordinator() {
  coordinator_ = 0;
  clear_has_coordinator();
}
inline ::google::protobuf::int32 SystemConfProto::coordinator() const {
  return coordinator_;
}
inline void SystemConfProto::set_coordinator(::google::protobuf::int32 value) {
  set_has_coordinator();
  coordinator_ = value;
}

// required int32 worker_start = 2;
inline bool SystemConfProto::has_worker_start() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void SystemConfProto::set_has_worker_start() {
  _has_bits_[0] |= 0x00000002u;
}
inline void SystemConfProto::clear_has_worker_start() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void SystemConfProto::clear_worker_start() {
  worker_start_ = 0;
  clear_has_worker_start();
}
inline ::google::protobuf::int32 SystemConfProto::worker_start() const {
  return worker_start_;
}
inline void SystemConfProto::set_worker_start(::google::protobuf::int32 value) {
  set_has_worker_start();
  worker_start_ = value;
}

// required int32 worker_end = 3;
inline bool SystemConfProto::has_worker_end() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void SystemConfProto::set_has_worker_end() {
  _has_bits_[0] |= 0x00000004u;
}
inline void SystemConfProto::clear_has_worker_end() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void SystemConfProto::clear_worker_end() {
  worker_end_ = 0;
  clear_has_worker_end();
}
inline ::google::protobuf::int32 SystemConfProto::worker_end() const {
  return worker_end_;
}
inline void SystemConfProto::set_worker_end(::google::protobuf::int32 value) {
  set_has_worker_end();
  worker_end_ = value;
}

// optional int32 memory_start = 4;
inline bool SystemConfProto::has_memory_start() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void SystemConfProto::set_has_memory_start() {
  _has_bits_[0] |= 0x00000008u;
}
inline void SystemConfProto::clear_has_memory_start() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void SystemConfProto::clear_memory_start() {
  memory_start_ = 0;
  clear_has_memory_start();
}
inline ::google::protobuf::int32 SystemConfProto::memory_start() const {
  return memory_start_;
}
inline void SystemConfProto::set_memory_start(::google::protobuf::int32 value) {
  set_has_memory_start();
  memory_start_ = value;
}

// optional int32 memory_end = 5;
inline bool SystemConfProto::has_memory_end() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void SystemConfProto::set_has_memory_end() {
  _has_bits_[0] |= 0x00000010u;
}
inline void SystemConfProto::clear_has_memory_end() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void SystemConfProto::clear_memory_end() {
  memory_end_ = 0;
  clear_has_memory_end();
}
inline ::google::protobuf::int32 SystemConfProto::memory_end() const {
  return memory_end_;
}
inline void SystemConfProto::set_memory_end(::google::protobuf::int32 value) {
  set_has_memory_end();
  memory_end_ = value;
}

// optional int32 disk_start = 6;
inline bool SystemConfProto::has_disk_start() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void SystemConfProto::set_has_disk_start() {
  _has_bits_[0] |= 0x00000020u;
}
inline void SystemConfProto::clear_has_disk_start() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void SystemConfProto::clear_disk_start() {
  disk_start_ = 0;
  clear_has_disk_start();
}
inline ::google::protobuf::int32 SystemConfProto::disk_start() const {
  return disk_start_;
}
inline void SystemConfProto::set_disk_start(::google::protobuf::int32 value) {
  set_has_disk_start();
  disk_start_ = value;
}

// optional int32 disk_end = 7;
inline bool SystemConfProto::has_disk_end() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void SystemConfProto::set_has_disk_end() {
  _has_bits_[0] |= 0x00000040u;
}
inline void SystemConfProto::clear_has_disk_end() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void SystemConfProto::clear_disk_end() {
  disk_end_ = 0;
  clear_has_disk_end();
}
inline ::google::protobuf::int32 SystemConfProto::disk_end() const {
  return disk_end_;
}
inline void SystemConfProto::set_disk_end(::google::protobuf::int32 value) {
  set_has_disk_end();
  disk_end_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace lapis

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_lapis_2eproto__INCLUDED
