// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cluster.proto

#ifndef PROTOBUF_cluster_2eproto__INCLUDED
#define PROTOBUF_cluster_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace singa {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_cluster_2eproto();
void protobuf_AssignDesc_cluster_2eproto();
void protobuf_ShutdownFile_cluster_2eproto();

class ClusterProto;

// ===================================================================

class ClusterProto : public ::google::protobuf::Message {
 public:
  ClusterProto();
  virtual ~ClusterProto();

  ClusterProto(const ClusterProto& from);

  inline ClusterProto& operator=(const ClusterProto& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ClusterProto& default_instance();

  void Swap(ClusterProto* other);

  // implements Message ----------------------------------------------

  ClusterProto* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ClusterProto& from);
  void MergeFrom(const ClusterProto& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 server_start = 1 [default = 0];
  inline bool has_server_start() const;
  inline void clear_server_start();
  static const int kServerStartFieldNumber = 1;
  inline ::google::protobuf::int32 server_start() const;
  inline void set_server_start(::google::protobuf::int32 value);

  // optional int32 server_end = 2 [default = 1];
  inline bool has_server_end() const;
  inline void clear_server_end();
  static const int kServerEndFieldNumber = 2;
  inline ::google::protobuf::int32 server_end() const;
  inline void set_server_end(::google::protobuf::int32 value);

  // optional int32 worker_start = 3;
  inline bool has_worker_start() const;
  inline void clear_worker_start();
  static const int kWorkerStartFieldNumber = 3;
  inline ::google::protobuf::int32 worker_start() const;
  inline void set_worker_start(::google::protobuf::int32 value);

  // optional int32 worker_end = 4;
  inline bool has_worker_end() const;
  inline void clear_worker_end();
  static const int kWorkerEndFieldNumber = 4;
  inline ::google::protobuf::int32 worker_end() const;
  inline void set_worker_end(::google::protobuf::int32 value);

  // optional int32 group_size = 5 [default = 1];
  inline bool has_group_size() const;
  inline void clear_group_size();
  static const int kGroupSizeFieldNumber = 5;
  inline ::google::protobuf::int32 group_size() const;
  inline void set_group_size(::google::protobuf::int32 value);

  // required string workspace = 6;
  inline bool has_workspace() const;
  inline void clear_workspace();
  static const int kWorkspaceFieldNumber = 6;
  inline const ::std::string& workspace() const;
  inline void set_workspace(const ::std::string& value);
  inline void set_workspace(const char* value);
  inline void set_workspace(const char* value, size_t size);
  inline ::std::string* mutable_workspace();
  inline ::std::string* release_workspace();
  inline void set_allocated_workspace(::std::string* workspace);

  // optional string vis_subfolder = 7 [default = "vis"];
  inline bool has_vis_subfolder() const;
  inline void clear_vis_subfolder();
  static const int kVisSubfolderFieldNumber = 7;
  inline const ::std::string& vis_subfolder() const;
  inline void set_vis_subfolder(const ::std::string& value);
  inline void set_vis_subfolder(const char* value);
  inline void set_vis_subfolder(const char* value, size_t size);
  inline ::std::string* mutable_vis_subfolder();
  inline ::std::string* release_vis_subfolder();
  inline void set_allocated_vis_subfolder(::std::string* vis_subfolder);

  // optional string log_subfolder = 8 [default = "log"];
  inline bool has_log_subfolder() const;
  inline void clear_log_subfolder();
  static const int kLogSubfolderFieldNumber = 8;
  inline const ::std::string& log_subfolder() const;
  inline void set_log_subfolder(const ::std::string& value);
  inline void set_log_subfolder(const char* value);
  inline void set_log_subfolder(const char* value, size_t size);
  inline ::std::string* mutable_log_subfolder();
  inline ::std::string* release_log_subfolder();
  inline void set_allocated_log_subfolder(::std::string* log_subfolder);

  // optional bool synchronous = 9 [default = false];
  inline bool has_synchronous() const;
  inline void clear_synchronous();
  static const int kSynchronousFieldNumber = 9;
  inline bool synchronous() const;
  inline void set_synchronous(bool value);

  // @@protoc_insertion_point(class_scope:singa.ClusterProto)
 private:
  inline void set_has_server_start();
  inline void clear_has_server_start();
  inline void set_has_server_end();
  inline void clear_has_server_end();
  inline void set_has_worker_start();
  inline void clear_has_worker_start();
  inline void set_has_worker_end();
  inline void clear_has_worker_end();
  inline void set_has_group_size();
  inline void clear_has_group_size();
  inline void set_has_workspace();
  inline void clear_has_workspace();
  inline void set_has_vis_subfolder();
  inline void clear_has_vis_subfolder();
  inline void set_has_log_subfolder();
  inline void clear_has_log_subfolder();
  inline void set_has_synchronous();
  inline void clear_has_synchronous();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 server_start_;
  ::google::protobuf::int32 server_end_;
  ::google::protobuf::int32 worker_start_;
  ::google::protobuf::int32 worker_end_;
  ::std::string* workspace_;
  ::std::string* vis_subfolder_;
  static ::std::string* _default_vis_subfolder_;
  ::google::protobuf::int32 group_size_;
  bool synchronous_;
  ::std::string* log_subfolder_;
  static ::std::string* _default_log_subfolder_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(9 + 31) / 32];

  friend void  protobuf_AddDesc_cluster_2eproto();
  friend void protobuf_AssignDesc_cluster_2eproto();
  friend void protobuf_ShutdownFile_cluster_2eproto();

  void InitAsDefaultInstance();
  static ClusterProto* default_instance_;
};
// ===================================================================


// ===================================================================

// ClusterProto

// optional int32 server_start = 1 [default = 0];
inline bool ClusterProto::has_server_start() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ClusterProto::set_has_server_start() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ClusterProto::clear_has_server_start() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ClusterProto::clear_server_start() {
  server_start_ = 0;
  clear_has_server_start();
}
inline ::google::protobuf::int32 ClusterProto::server_start() const {
  return server_start_;
}
inline void ClusterProto::set_server_start(::google::protobuf::int32 value) {
  set_has_server_start();
  server_start_ = value;
}

// optional int32 server_end = 2 [default = 1];
inline bool ClusterProto::has_server_end() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ClusterProto::set_has_server_end() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ClusterProto::clear_has_server_end() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ClusterProto::clear_server_end() {
  server_end_ = 1;
  clear_has_server_end();
}
inline ::google::protobuf::int32 ClusterProto::server_end() const {
  return server_end_;
}
inline void ClusterProto::set_server_end(::google::protobuf::int32 value) {
  set_has_server_end();
  server_end_ = value;
}

// optional int32 worker_start = 3;
inline bool ClusterProto::has_worker_start() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ClusterProto::set_has_worker_start() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ClusterProto::clear_has_worker_start() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ClusterProto::clear_worker_start() {
  worker_start_ = 0;
  clear_has_worker_start();
}
inline ::google::protobuf::int32 ClusterProto::worker_start() const {
  return worker_start_;
}
inline void ClusterProto::set_worker_start(::google::protobuf::int32 value) {
  set_has_worker_start();
  worker_start_ = value;
}

// optional int32 worker_end = 4;
inline bool ClusterProto::has_worker_end() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void ClusterProto::set_has_worker_end() {
  _has_bits_[0] |= 0x00000008u;
}
inline void ClusterProto::clear_has_worker_end() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void ClusterProto::clear_worker_end() {
  worker_end_ = 0;
  clear_has_worker_end();
}
inline ::google::protobuf::int32 ClusterProto::worker_end() const {
  return worker_end_;
}
inline void ClusterProto::set_worker_end(::google::protobuf::int32 value) {
  set_has_worker_end();
  worker_end_ = value;
}

// optional int32 group_size = 5 [default = 1];
inline bool ClusterProto::has_group_size() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void ClusterProto::set_has_group_size() {
  _has_bits_[0] |= 0x00000010u;
}
inline void ClusterProto::clear_has_group_size() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void ClusterProto::clear_group_size() {
  group_size_ = 1;
  clear_has_group_size();
}
inline ::google::protobuf::int32 ClusterProto::group_size() const {
  return group_size_;
}
inline void ClusterProto::set_group_size(::google::protobuf::int32 value) {
  set_has_group_size();
  group_size_ = value;
}

// required string workspace = 6;
inline bool ClusterProto::has_workspace() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void ClusterProto::set_has_workspace() {
  _has_bits_[0] |= 0x00000020u;
}
inline void ClusterProto::clear_has_workspace() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void ClusterProto::clear_workspace() {
  if (workspace_ != &::google::protobuf::internal::kEmptyString) {
    workspace_->clear();
  }
  clear_has_workspace();
}
inline const ::std::string& ClusterProto::workspace() const {
  return *workspace_;
}
inline void ClusterProto::set_workspace(const ::std::string& value) {
  set_has_workspace();
  if (workspace_ == &::google::protobuf::internal::kEmptyString) {
    workspace_ = new ::std::string;
  }
  workspace_->assign(value);
}
inline void ClusterProto::set_workspace(const char* value) {
  set_has_workspace();
  if (workspace_ == &::google::protobuf::internal::kEmptyString) {
    workspace_ = new ::std::string;
  }
  workspace_->assign(value);
}
inline void ClusterProto::set_workspace(const char* value, size_t size) {
  set_has_workspace();
  if (workspace_ == &::google::protobuf::internal::kEmptyString) {
    workspace_ = new ::std::string;
  }
  workspace_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* ClusterProto::mutable_workspace() {
  set_has_workspace();
  if (workspace_ == &::google::protobuf::internal::kEmptyString) {
    workspace_ = new ::std::string;
  }
  return workspace_;
}
inline ::std::string* ClusterProto::release_workspace() {
  clear_has_workspace();
  if (workspace_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = workspace_;
    workspace_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void ClusterProto::set_allocated_workspace(::std::string* workspace) {
  if (workspace_ != &::google::protobuf::internal::kEmptyString) {
    delete workspace_;
  }
  if (workspace) {
    set_has_workspace();
    workspace_ = workspace;
  } else {
    clear_has_workspace();
    workspace_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional string vis_subfolder = 7 [default = "vis"];
inline bool ClusterProto::has_vis_subfolder() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void ClusterProto::set_has_vis_subfolder() {
  _has_bits_[0] |= 0x00000040u;
}
inline void ClusterProto::clear_has_vis_subfolder() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void ClusterProto::clear_vis_subfolder() {
  if (vis_subfolder_ != _default_vis_subfolder_) {
    vis_subfolder_->assign(*_default_vis_subfolder_);
  }
  clear_has_vis_subfolder();
}
inline const ::std::string& ClusterProto::vis_subfolder() const {
  return *vis_subfolder_;
}
inline void ClusterProto::set_vis_subfolder(const ::std::string& value) {
  set_has_vis_subfolder();
  if (vis_subfolder_ == _default_vis_subfolder_) {
    vis_subfolder_ = new ::std::string;
  }
  vis_subfolder_->assign(value);
}
inline void ClusterProto::set_vis_subfolder(const char* value) {
  set_has_vis_subfolder();
  if (vis_subfolder_ == _default_vis_subfolder_) {
    vis_subfolder_ = new ::std::string;
  }
  vis_subfolder_->assign(value);
}
inline void ClusterProto::set_vis_subfolder(const char* value, size_t size) {
  set_has_vis_subfolder();
  if (vis_subfolder_ == _default_vis_subfolder_) {
    vis_subfolder_ = new ::std::string;
  }
  vis_subfolder_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* ClusterProto::mutable_vis_subfolder() {
  set_has_vis_subfolder();
  if (vis_subfolder_ == _default_vis_subfolder_) {
    vis_subfolder_ = new ::std::string(*_default_vis_subfolder_);
  }
  return vis_subfolder_;
}
inline ::std::string* ClusterProto::release_vis_subfolder() {
  clear_has_vis_subfolder();
  if (vis_subfolder_ == _default_vis_subfolder_) {
    return NULL;
  } else {
    ::std::string* temp = vis_subfolder_;
    vis_subfolder_ = const_cast< ::std::string*>(_default_vis_subfolder_);
    return temp;
  }
}
inline void ClusterProto::set_allocated_vis_subfolder(::std::string* vis_subfolder) {
  if (vis_subfolder_ != _default_vis_subfolder_) {
    delete vis_subfolder_;
  }
  if (vis_subfolder) {
    set_has_vis_subfolder();
    vis_subfolder_ = vis_subfolder;
  } else {
    clear_has_vis_subfolder();
    vis_subfolder_ = const_cast< ::std::string*>(_default_vis_subfolder_);
  }
}

// optional string log_subfolder = 8 [default = "log"];
inline bool ClusterProto::has_log_subfolder() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void ClusterProto::set_has_log_subfolder() {
  _has_bits_[0] |= 0x00000080u;
}
inline void ClusterProto::clear_has_log_subfolder() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void ClusterProto::clear_log_subfolder() {
  if (log_subfolder_ != _default_log_subfolder_) {
    log_subfolder_->assign(*_default_log_subfolder_);
  }
  clear_has_log_subfolder();
}
inline const ::std::string& ClusterProto::log_subfolder() const {
  return *log_subfolder_;
}
inline void ClusterProto::set_log_subfolder(const ::std::string& value) {
  set_has_log_subfolder();
  if (log_subfolder_ == _default_log_subfolder_) {
    log_subfolder_ = new ::std::string;
  }
  log_subfolder_->assign(value);
}
inline void ClusterProto::set_log_subfolder(const char* value) {
  set_has_log_subfolder();
  if (log_subfolder_ == _default_log_subfolder_) {
    log_subfolder_ = new ::std::string;
  }
  log_subfolder_->assign(value);
}
inline void ClusterProto::set_log_subfolder(const char* value, size_t size) {
  set_has_log_subfolder();
  if (log_subfolder_ == _default_log_subfolder_) {
    log_subfolder_ = new ::std::string;
  }
  log_subfolder_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* ClusterProto::mutable_log_subfolder() {
  set_has_log_subfolder();
  if (log_subfolder_ == _default_log_subfolder_) {
    log_subfolder_ = new ::std::string(*_default_log_subfolder_);
  }
  return log_subfolder_;
}
inline ::std::string* ClusterProto::release_log_subfolder() {
  clear_has_log_subfolder();
  if (log_subfolder_ == _default_log_subfolder_) {
    return NULL;
  } else {
    ::std::string* temp = log_subfolder_;
    log_subfolder_ = const_cast< ::std::string*>(_default_log_subfolder_);
    return temp;
  }
}
inline void ClusterProto::set_allocated_log_subfolder(::std::string* log_subfolder) {
  if (log_subfolder_ != _default_log_subfolder_) {
    delete log_subfolder_;
  }
  if (log_subfolder) {
    set_has_log_subfolder();
    log_subfolder_ = log_subfolder;
  } else {
    clear_has_log_subfolder();
    log_subfolder_ = const_cast< ::std::string*>(_default_log_subfolder_);
  }
}

// optional bool synchronous = 9 [default = false];
inline bool ClusterProto::has_synchronous() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void ClusterProto::set_has_synchronous() {
  _has_bits_[0] |= 0x00000100u;
}
inline void ClusterProto::clear_has_synchronous() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void ClusterProto::clear_synchronous() {
  synchronous_ = false;
  clear_has_synchronous();
}
inline bool ClusterProto::synchronous() const {
  return synchronous_;
}
inline void ClusterProto::set_synchronous(bool value) {
  set_has_synchronous();
  synchronous_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace singa

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_cluster_2eproto__INCLUDED
